import React from 'react'


export const metadata = {
  title: 'My Todo',
  description: 'Generated by create next app',
}

export default function MyTodoLayout({ children }) {
  return (
    <div>
        {children}
    </div>
  )
}
